title: moon_log
email: mun.js@aol.com
description: >- # this means to ignore newlines until "baseurl:"
  풀스택 인간이 되기 위해 미생의 삶을 살고 있는 지금
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: Junsang-Mun

minimal_mistakes_skin: "dirt"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache

author:
  name    : "Junsang Mun"
  avatar  : "/assets/profile.png"
  bio     : "     "
  location: "Earth, Universe"
  email   : "mun.js@aol.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:mun.js@aol.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Junsang-Mun"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/junsang_mun"

